repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=nd,reacher,thist,ths,magent
          - --skip=assets/**/*
https://m.xxxsopp.xyz/api/v1/client/subscribe?token=5b3319358a8cf1633f61c123700fad81